version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your-secret-key-for-docker
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=workout_predictor
      - POSTGRES_USER=workout_admin
      - POSTGRES_PASSWORD=workout_pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
  static_volume:
